In [1]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("original arrays")
print(a)
print(b)
print("\n vector addition")
print(a+b)
print("\n vector subtraction")
print(a-b)
print("\n vector multipication")
print(a*b)
print("\n vector division")
print(a/b)
print("\n vector dot product ")
print(a.dot(b))
print("\n scalar mulitiplication")
sclr=5
print("scalar value=",sclr)


original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

 vector addition
[12 24 35 48 60]

 vector subtraction
[ 8 16 25 32 40]

 vector multipication
[ 20  80 150 320 500]

 vector division
[5. 5. 6. 5. 5.]

 vector dot product 
1070

 scalar mulitiplication
scalar value= 5


In [ ]:
def my_func(x,y):
    #retun x-y if x>y,otherwise return x+y
    if x>y:
        return x-y
    else:    