In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
print(arr)
x=np.where(arr==4)
print(x)
arr=np.array([1,2,3,4,5,6,8])
x=np.where(arr%2==0)
print(arr)
print(x)
arr=np.array([3,2,0,1])
print("\noriginal array",arr)
print("\nsorted array",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\noriginal array",arr)
print("\nsorted array",np.sort(arr))
#Filter
arr=np.array([41,42,43,44])
x =[True,False,True,False]
newarr = arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)
arr=np.array([41,42,43,44])
filter_arr = arr > 42 
newarr = arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filter_arr)
print("\nNew array:",newarr)

[1 2 3 4 5 6 4]
(array([3, 6]),)
[1 2 3 4 5 6 8]
(array([1, 3, 5, 6]),)

original array [3 2 0 1]

sorted array [0 1 2 3]

original array [[3 2 4]
 [5 0 1]]

sorted array [[2 3 4]
 [0 1 5]]

Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]

Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

New array: [43 44]
