In [2]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Oringinal array:\n",arr)
print("\n Everyother rows :\n",arr[0:3:2])
arr =np.array([1,2,3,4,5,6,7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array:arr[::2]\n",arr[::2])
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp =arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:\n",temp)
x= arr[[0,1,2,3],[3,2,1,0]]
print("\nElement at indices(0,3),(1,2),(2,1),""(3,0):\n",x)
cond = arr>2
temp = arr[cond]
print("\nElement greater than 2:\n",temp)
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)
arr3=np.hstack((arr1,arr2))
print(arr3)
arr4=np.vstack((arr1,arr2))
print(arr4)
arr5=np.dstack((arr1,arr2))
print(arr5)
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)
print(arr6[0])
print(arr6[1])
print(arr6[2])




Oringinal array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

 Everyother rows :
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]

Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:arr[::2]
 [1 3 5 7]

Array with first 2 rows and 3 columns:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]

Element at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]

Element greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
